#! /bin/bash

IMAGE_NAME=xlsx2csv
IMAGE_TAG=`date "+%Y.%m.%d"`

BUILD_PATH=`dirname "$0"`

docker build --tag ${IMAGE_NAME}:${IMAGE_TAG} ${BUILD_PATH} && \
docker image tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
