#! /bin/sh

echo '----------- docker -----------'
echo 'command line arguments:' $@
echo 'workdir:' `pwd` ; ls -lh

echo '------- converter args -------'
TARGET_FILE=$1
OUTPUT_FORMAT=$2
OUTPUT_FILE=$3

OUTPUT_PATH=`dirname ${OUTPUT_FILE}`

echo 'target file:' ${TARGET_FILE}
echo 'output file:' ${OUTPUT_FILE}
echo 'output path:' ${OUTPUT_PATH}
echo 'output format:' ${OUTPUT_FORMAT}

echo '---------- converter ----------'
pandoc --to ${OUTPUT_FORMAT} --output ${OUTPUT_FILE} --extract-media ${OUTPUT_PATH} ${TARGET_FILE}

if [[ -d ${OUTPUT_PATH}/media ]]; then
 	mv ${OUTPUT_PATH}/media ${OUTPUT_PATH}/proposal_media && \
 		sed -i.sedbackup "s|${OUTPUT_PATH}/media/|proposal_media/|g" ${OUTPUT_FILE} && \
		rm ${OUTPUT_FILE}.sedbackup
fi

echo '------ printing outputs ------'
# echo "::set-output name=output-file-root::${OUTPUT_FILE_ROOT}"

echo '---------- finished ----------'
