name: Convert proposal.docx

# define when the workflow should run
on:
  workflow_call:
    inputs:
      target-file:
        required: true
        type: string
        default: 'babs/docs/proposal.docx'

# set up environment variables
env:
  OUTPUT_FILE: 'babs/docs/proposal.md'
  OUTPUT_FORMAT: 'gfm'

# define the work to be done
jobs:
  convert-proposal-document:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        id: checkout-repo
        uses: actions/checkout@v3

      - name: check proposal exists
        id: target-file-existence
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ inputs.target-file }}

      - name: run conversion using pandoc
        id: convert-target-file
        uses: docker://pandoc/core:2.9
        if: steps.target-file-existence.outputs.files_exists == 'true'
        with:
          args: "--to ${{ env.OUTPUT_FORMAT }} --output ${{ env.OUTPUT_FILE }} --extract-media babs/docs ${{ inputs.target-file }}" # gets appended to pandoc command

      - name: fix media links in markdown
        id: fix-media-links
        if: steps.convert-target-file.outcome == 'success'
        run: |
          date >> babs/docs/proposal.md
          mv babs/docs/media babs/docs/proposal_media
          sed --in-place 's|babs/docs/media/|proposal_media/|g' ${{ env.OUTPUT_FILE }}

      - name: list files in expected output directory
        if: steps.convert-target-file.outcome == 'failure'
        run: ls babs/docs

      - name: commit converted proposal
        if: steps.convert-target-file.outcome == 'success'
        run: |

          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit --message "proposal.docx converted"
          git push origin HEAD:main
