name: Convert an experiment table xlsx to csv

# when a commit includes a experiment_table.xlsx file
on:
  push:
    paths:
      - 'babs/docs/experiment_table.xlsx'
  workflow_dispatch:
  workflow_call:

# set up environment variables
env:
  INPUT_FILE: 'babs/docs/experiment_table.xlsx'
  OUTPUT_FILE: 'babs/docs/experiment_table.csv'
  OUTPUT_FORMAT: 'csv'

# define the work to be done
jobs:
  convert-experiment-table:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: check experiment table exists
        id: target_file_exists
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ env.INPUT_FILE }}
      - name: run xlsx2csv
        id: convert_input_file
        uses: docker://christopherbarrington/xlsx2csv:2022.10.01
        if: steps.target_file_exists.outputs.files_exists == 'true'
        with:
          args: ${{ env.INPUT_FILE }} ${{ env.OUTPUT_FILE }}
      - name: list files in expected output directory
        if: steps.convert_input_file.outcome == 'failure'
        run: ls babs/docs
      - name: commit converted experiment table
        id: commit_all_changes
        if: steps.convert_input_file.outcome == 'success'
        run: |
          git branch --all
          git remote --verbose
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "babs-o-matic converted ${{ env.INPUT_FILE }} to ${{ env.OUTPUT_FORMAT }}"
          git push origin HEAD:main
